### ISSUE TITLE
No such file or directory: '/Users/prateek/8thSem/prid_2011/recs/image_train_even0.lst' 

### ISSUE THREAD

**Issue by prateekagarwal3** [TuSimple/rl-multishot-reid#1]
In the second step of how to run the code, it is written about preparing data files and no such description is mentioned, could you please explain upon the same.

**Comment by SMCamila** [comment]
Please refer the 'Usage' paragraph in README. You should run these python scripts for preprocessing. And please make sure that the path ''/Users/prateek/8thSem/prid_2011/recs/' exist.

**Comment by prateekagarwal3** [comment]
The path does exist in the directory, but the issue now I am getting is that im2rec is located in the bin folder in your case, but is located as a python file in my mxnet directory structure, and the os.system command in your preprocessing file is running properly.

**Comment by prateekagarwal3** [comment]
I did refer to the 'Usage' paragraph of the readme, I was able to get away with this error.
