### ISSUE TITLE
mxnet/bin/im2rec does not exist in my installation folder. 

### ISSUE THREAD

**Issue by prateekagarwal3** [TuSimple/rl-multishot-reid#2]
Instead, mxnet/tools/im2rec.py is there, please explain how to modify the pre-processing file to run it successfully. I installed mxnet using pip install mxnet==0.11.0 and also tried version 1.0.0 but none of them have a bin folder.
Maybe you could help me by telling what mxnet version had you used?

**Comment by SMCamila** [comment]
Sorry for the late reply and thank you for you patience.
The code is tested on mxnet on commit e06c55, which is an old version of mxnet. We've mentioned this in Preparations. You can get the binary file im2rec in this mxnet commit.

Updates: It seems like that e06c55 is **not a public commit of mxnet**. I'm the maintainer and I wrote these code under a special environment while I was an intern.  And I left now. For the time being I'm trying to rebuild this project with newest public mxnet version and make sure all these things work. Please wait for our new commit.

**Comment by prateekagarwal3** [comment]
Yeah, I did notice about the commit being mentioned, but we couldn't find the im2rec file and so raised an issue, now that you are rebuilding it on the current version of mxnet will be waiting for it. Thanks for the help.

**Comment by InnovArul** [comment]
Any update regarding this?
